version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
#    volumes:
#      #    - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb
#    networks:
#      - db